version: '2'

# node application for ecard-api
services:
    ecard-api:
        build: .
        image: ynuae/ecard-api
        ports:
          - "50013:3000"
        environment:
          - DATABASE_HOST
          - USER=ecard
          - PASSWORD
          - DATABASE
          - SECRET
        restart: always
